name: cacherun
on:
  push:
jobs:
  cachetesting:
    runs-on: ubuntu-latest
    steps:
      - name: cache pip download
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt' )}}
          restore-keys: |
            pip-
      - name: install pip
        run: pip install -r requirements.txt

