name: cacherun

on:
  push:

jobs:
  cachetesting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check requirements file
        run: |
          pwd
          ls -la
          cat requirements.txt

      - name: Cache pip download
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install pip packages
        run: pip install -r requirements.txt
