name: testing
on:
  push:
jobs:
  testingjob:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: print
        run: |
          uname -a
          ls -la
      - name: count
        run: find . -type f | wc -l


