name: artifact
on: push
jobs:
  testartifact:
    runs-on: ubuntu-latest
    steps:
      - name: actionv 
        uses: actions/checkout@v4

      - name: reportdate
        run: |
          date > report.txt
          
          
      - name: uploader
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt
          retention-days: 5

